module.exports = {
    name: 'invite',
    alias: ['link', 'invitelink', 'ഇൻവൈറ്റ്'],
    desc: 'Get group invite link',
    category: 'group',
    execute: async (sock, msg, args, { config }) => {
        const isGroup = msg.key.remoteJid.endsWith('@g.us');
        
        if (!isGroup) {
            await sock.sendMessage(msg.key.remoteJid, {
                text: '❌ This command only works in groups!'
            }, { quoted: msg });
            return;
        }

        try {
            // Get group info
            const groupMetadata = await sock.groupMetadata(msg.key.remoteJid);
            
            // Check if bot is admin (needed for invite link)
            const botIsAdmin = groupMetadata.participants.find(p => p.id === sock.user.id)?.admin;
            
            if (!botIsAdmin) {
                await sock.sendMessage(msg.key.remoteJid, {
                    text: '❌ I need to be admin to generate invite link!\n' +
                          'Please make me admin first.'
                }, { quoted: msg });
                return;
            }

            // Generate invite code
            const inviteCode = await sock.groupInviteCode(msg.key.remoteJid);
            const inviteLink = `https://chat.whatsapp.com/${inviteCode}`;
            
            // Get group info
            const groupName = groupMetadata.subject;
            const memberCount = groupMetadata.participants.length;
            const adminsCount = groupMetadata.participants.filter(p => p.admin).length;
            
            await sock.sendMessage(msg.key.remoteJid, {
                text: `🔗 *GROUP INVITE LINK*\n\n` +
                      `📛 Group: ${groupName}\n` +
                      `👥 Members: ${memberCount}\n` +
                      `👑 Admins: ${adminsCount}\n\n` +
                      `*Invite Link:*\n${inviteLink}\n\n` +
                      `⚠️ *IMPORTANT:*\n` +
                      `• Link expires in 72 hours\n` +
                      `• Max 1024 members\n` +
                      `• Share carefully!\n\n` +
                      `Generated by: ${config.botName}`
            }, { quoted: msg });

        } catch (error) {
            console.error('Invite error:', error);
            await sock.sendMessage(msg.key.remoteJid, {
                text: `❌ Failed to get invite link: ${error.message}\n\n` +
                      `Make sure I'm admin in the group.`
            }, { quoted: msg });
        }
    }
};